
=pod

=encoding utf8

=head1 PocketIO

L<PocketIO> is a server implementation of SocketIO in Perl.

All the transports are supported.

    WebSocket
    Adobe® Flash® Socket
    AJAX long polling
    AJAX multipart streaming
    Forever Iframe
    JSONP Polling

=head1 SocketIO

More information about SocketIO you can find on the website L<http://socket.io/>, or
on GitHub L<https://github.com/LearnBoost/Socket.IO>.

=head1 EXAMPLE

Below is an example similar to Socket.IO-node example chat. To run this example,
you need to make the following simple steps:

=over 4

=item 1. Clone somewhere L<https://github.com/LearnBoost/Socket.IO-node>.

=item 2. Switch to the C<06> branch: C<cd Socket.IO-node ; git checkout 06>

=item 3. Save the shown F<.psgi> file, changing I<$path_to_socket_io> so it points to the Socket.IO-node files:

    use Plack::App::File;
    use Plack::Builder;
    use Plack::Middleware::Static;

    use PocketIO;

    my $path_to_socket_io = "/path/to/Socket.IO-node";

    builder {
        mount '/socket.io/socket.io.js' => Plack::App::File->new(
            file => "$path_to_socket_io/support/socket.io-client/socket.io.js");

        mount '/socket.io/lib' => Plack::App::File->new(
            root => "$path_to_socket_io/support/socket.io-client/lib");

        mount '/socket.io' => PocketIO->new(
            handler => sub {
                my $self = shift;

                $self->on_message(
                    sub {
                        my $self = shift;
                        my ($message) = @_;

                        $self->send_broadcast(
                            {message => [$self->id, $message]});
                    }
                );

                $self->on_disconnect(
                    sub {
                        $self->send_broadcast(
                            {announcement => $self->id . ' disconnected'});
                    }
                );

                $self->send_message({buffer => []});

                $self->send_broadcast(
                    {announcement => $self->id . ' connected'});
            }
        );

        mount '/' => builder {
            enable "Static",
              path => qr/\.(?:js|css|jpe?g|gif|png|swf|ico)$/,
              root => "$path_to_socket_io/example";

            enable "SimpleLogger", level => 'debug';

            sub {
                [   200,
                    ['Content-Type' => 'text/html'],
                    ['Open <a href="/chat.html">chat</a>.']
                ];
            };
        };
    };

=item 4. Start L<Twiggy> or L<Fliggy> (same as L<Twiggy> but with inlined Flash Policy server)

    $ sudo flash-policy-server &
    $ twiggy chat.psgi --listen :8080

    or

    $ fliggy chat.psgi --listen :8080

=item 5. Point your browser to

    http://localhost:8080

=back

=head1 TLS/SSL

For TLS/SSL a secure proxy is needed. C<stunnel> or L<App::TLSMe> is
recommended.

=head1 DISCLAIMER

This application is in a very beta stage. API will be probably changed.

=head1 CREDITS

Socket.IO author(s) and contributors.

=head1 AUTHOR

Viacheslav Tykhanovskyi, C<vti@cpan.org>.

=head1 COPYRIGHT

Copyright (C) 2011, Viacheslav Tykhanovskyi

This program is free software, you can redistribute it and/or modify it under
the terms of the Artistic License version 2.0.

=cut
